import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'http',
        hostname: 'localhost',
        port: '1337',
        pathname: '/uploads/**'
      },
      {
        protocol: 'https',
        hostname: 'competent-beef-d2ccc79b9b.media.strapiapp.com'
      },
      {
        protocol: 'https',
        hostname: 'competent-beef-d2ccc79b9b.strapiapp.com'
      }
    ]
  },
  async redirects() {
    return [
      { source: '/careers', destination: '/jobs', permanent: true },
      { source: '/careers.php', destination: '/jobs', permanent: true },
      { source: '/sitemap', destination: '/sitemap.xml', permanent: true },
      { source: '/view-our-facility', destination: '/', permanent: true },
      { source: '/view-our-facility.php', destination: '/', permanent: true },
      { source: '/pendarvis-tour-video', destination: '/', permanent: true },
      { source: '/pendarvis-tour-video.php', destination: '/', permanent: true },
      { source: '/new-ownership', destination: '/', permanent: true },
      { source: '/new-ownership.php', destination: '/', permanent: true },
      { source: '/summer-rebate-program', destination: '/', permanent: true },
      { source: '/summer-rebate-program.php', destination: '/', permanent: true },

      { source: '/ask-a-question', destination: '/contact-us', permanent: true },
      { source: '/ask-a-question.php', destination: '/contact-us', permanent: true },
      { source: '/rma-request', destination: '/contact-us', permanent: true },
      { source: '/rma-request.php', destination: '/contact-us', permanent: true },

      { source: '/request-a-quote', destination: '/quote', permanent: true },
      { source: '/request-a-quote.php', destination: '/quote', permanent: true },
      { source: '/request-3d-quote', destination: '/quote', permanent: true },
      { source: '/request-3d-quote.php', destination: '/quote', permanent: true },

      { source: '/itar-compliance', destination: '/quality', permanent: true },
      { source: '/itar-compliance.php', destination: '/quality', permanent: true },
      { source: '/quality-policy', destination: '/quality', permanent: true },
      { source: '/quality-policy.php', destination: '/quality', permanent: true },
      { source: '/supplier-quality-clauses', destination: '/quality', permanent: true },
      { source: '/supplier-quality-clauses.php', destination: '/quality', permanent: true },
      { source: '/as9100d-certification', destination: '/quality', permanent: true },
      { source: '/as9100d-certification.php', destination: '/quality', permanent: true },
      { source: '/privacy-policy', destination: '/quality', permanent: true },
      { source: '/privacy-policy.php', destination: '/quality', permanent: true },

      { source: '/welding-services', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/welding-services.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/tig-welding', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/tig-welding.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/welding', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/welding.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/aluminum-welding', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/aluminum-welding.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/mig-welding', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/mig-welding.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/stainless-steel-welding', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/stainless-steel-welding.php', destination: '/portfolio/services/certified-welding', permanent: true },
      { source: '/portfolio/services/machining', destination: '/portfolio/services/certified-welding', permanent: true },

      { source: '/sheet-metal-machining', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/sheet-metal-machining.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/structural-steel-fabrication', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/structural-steel-fabrication.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/carbon-steel-fabrication', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/carbon-steel-fabrication.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/stainless-steel-fabrication', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/stainless-steel-fabrication.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/custom-laser-cutting', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/custom-laser-cutting.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/waterjet-cutting', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/waterjet-cutting.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/cnc-punching', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/cnc-punching.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/metal-fabrication', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/metal-fabrication.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/aluminum-fabrication', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/aluminum-fabrication.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/laser-cutting-services', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/laser-cutting-services.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/metal-punching', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/metal-punching.php', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/aluminum-machining', destination: '/portfolio/services/sheet-metal', permanent: true },
      { source: '/aluminum-machining.php', destination: '/portfolio/services/sheet-metal', permanent: true },

      { source: '/finishing-services', destination: '/portfolio/services/finishing-assembling', permanent: true },
      { source: '/finishing-services.php', destination: '/portfolio/services/finishing-assembling', permanent: true },

      { source: '/industries-served', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/industries-served.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/aerospace-and-defense', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/aerospace-and-defense.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/medical-and-emergency-services', destination: '/portfolio/featured-industries/industrial', permanent: true },
      { source: '/medical-and-emergency-services.php', destination: '/portfolio/featured-industries/industrial', permanent: true },
      { source: '/wastewater-treatment-and-disposal', destination: '/portfolio/featured-industries/wastewater-treatment', permanent: true },
      { source: '/wastewater-treatment-and-disposal.php', destination: '/portfolio/featured-industries/wastewater-treatment', permanent: true },
      { source: '/sewage-treatment-and-disposal', destination: '/portfolio/featured-industries/wastewater-treatment', permanent: true },
      { source: '/sewage-treatment-and-disposal.php', destination: '/portfolio/featured-industries/wastewater-treatment', permanent: true },
      { source: '/industrial', destination: '/portfolio/featured-industries/industrial', permanent: true },
      { source: '/industrial.php', destination: '/portfolio/featured-industries/industrial', permanent: true },
      { source: '/refinery-and-oil-well-equipment', destination: '/portfolio/featured-industries/energy', permanent: true },
      { source: '/refinery-and-oil-well-equipment.php', destination: '/portfolio/featured-industries/energy', permanent: true },
      { source: '/transportation', destination: '/portfolio/featured-industries/transit-infrastructure', permanent: true },
      { source: '/transportation.php', destination: '/portfolio/featured-industries/transit-infrastructure', permanent: true },

      { source: '/electrical-and-electronics', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/electrical-and-electronics.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/material-handling', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/material-handling.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/oceanographic', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/oceanographic.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/printing', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/printing.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/recreational', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/recreational.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/specialty-plastic', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/specialty-plastic.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/air-pollution-control', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/air-pollution-control.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/entertainment', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/entertainment.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/hazardous-waste-equipment', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/hazardous-waste-equipment.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/lighting', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/lighting.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/robotics', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/robotics.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/scientific-research', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },
      { source: '/scientific-research.php', destination: '/portfolio/featured-industries/aerospace-defence-space', permanent: true },

      { source: '/rodder', destination: '/portfolio', permanent: true },
      { source: '/rodder.php', destination: '/portfolio', permanent: true },
      { source: '/trac-projects', destination: '/portfolio', permanent: true },
      { source: '/trac-projects.php', destination: '/portfolio', permanent: true },
      { source: '/hyperloop-test-sled', destination: '/portfolio', permanent: true },
      { source: '/hyperloop-test-sled.php', destination: '/portfolio', permanent: true },
      { source: '/1000-holes', destination: '/portfolio', permanent: true },
      { source: '/1000-holes.php', destination: '/portfolio', permanent: true },
      { source: '/angel-stadium-of-anaheim', destination: '/portfolio', permanent: true },
      { source: '/angel-stadium-of-anaheim.php', destination: '/portfolio', permanent: true },
      { source: '/bio-boxes-clarifiers', destination: '/portfolio', permanent: true },
      { source: '/bio-boxes-clarifiers.php', destination: '/portfolio', permanent: true },
      { source: '/biomixers', destination: '/portfolio', permanent: true },
      { source: '/biomixers.php', destination: '/portfolio', permanent: true },
      { source: '/caltech', destination: '/portfolio', permanent: true },
      { source: '/caltech.php', destination: '/portfolio', permanent: true },
      { source: '/grating-project', destination: '/portfolio', permanent: true },
      { source: '/grating-project.php', destination: '/portfolio', permanent: true },
      { source: '/plastic-welder', destination: '/portfolio', permanent: true },
      { source: '/plastic-welder.php', destination: '/portfolio', permanent: true },
      { source: '/ss-other', destination: '/portfolio', permanent: true },
      { source: '/ss-other.php', destination: '/portfolio', permanent: true },
      { source: '/ss-piping-troughs', destination: '/portfolio', permanent: true },
      { source: '/ss-piping-troughs.php', destination: '/portfolio', permanent: true },
      { source: '/ss-products', destination: '/portfolio', permanent: true },
      { source: '/ss-products.php', destination: '/portfolio', permanent: true },
      { source: '/ss-tanks', destination: '/portfolio', permanent: true },
      { source: '/ss-tanks.php', destination: '/portfolio', permanent: true },
      { source: '/ss-tracks', destination: '/portfolio', permanent: true },
      { source: '/ss-tracks.php', destination: '/portfolio', permanent: true },
      { source: '/stonemills', destination: '/portfolio', permanent: true },
      { source: '/stonemills.php', destination: '/portfolio', permanent: true },
      { source: '/bio-boxes-and-clarifiers', destination: '/portfolio', permanent: true },
      { source: '/bio-boxes-and-clarifiers.php', destination: '/portfolio', permanent: true },
      { source: '/ss-piping-and-troughs', destination: '/portfolio', permanent: true },
      { source: '/ss-piping-and-troughs.php', destination: '/portfolio', permanent: true },
      { source: '/steel', destination: '/portfolio', permanent: true },
      { source: '/steel.php', destination: '/portfolio', permanent: true },
      { source: '/project-portfolio', destination: '/portfolio', permanent: true },
      { source: '/project-portfolio.php', destination: '/portfolio', permanent: true },
      { source: '/machinery-projects', destination: '/portfolio', permanent: true },
      { source: '/machinery-projects.php', destination: '/portfolio', permanent: true },
      { source: '/materials-we-work-with', destination: '/portfolio', permanent: true },
      { source: '/materials-we-work-with.php', destination: '/portfolio', permanent: true },
      { source: '/aluminum', destination: '/portfolio', permanent: true },
      { source: '/aluminum.php', destination: '/portfolio', permanent: true },
      { source: '/stainless-steel', destination: '/portfolio', permanent: true },
      { source: '/stainless-steel.php', destination: '/portfolio', permanent: true },
      { source: '/plastics', destination: '/portfolio', permanent: true },
      { source: '/plastics.php', destination: '/portfolio', permanent: true },
      { source: '/brass', destination: '/portfolio', permanent: true },
      { source: '/brass.php', destination: '/portfolio', permanent: true },
      { source: '/bronze', destination: '/portfolio', permanent: true },
      { source: '/bronze.php', destination: '/portfolio', permanent: true },
      { source: '/waterjet-cutting-contact', destination: '/portfolio', permanent: true },
      { source: '/waterjet-cutting-contact.php', destination: '/portfolio', permanent: true },
      { source: '/aluminum-6061', destination: '/portfolio', permanent: true },
      { source: '/aluminum-6061.php', destination: '/portfolio', permanent: true },
      { source: '/carbon-steel', destination: '/portfolio', permanent: true },
      { source: '/carbon-steel.php', destination: '/portfolio', permanent: true },
    ]
  }
}

export default nextConfig
